name = "Pushup"
license = "MIT"
licenselink = "https://github.com/adhocteam/pushup/blob/master/docs/themes/pushup/LICENSE"
description = "Theme for the main website of the Pushup web framework."
homepage = "https://gopushup.dev/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Paul Smith"
  homepage = "https://pauladamsmith.com/"
