name: Deploy Pushup website to Fly.io
on:
  workflow_run:
    workflows: ["Build and test"]
    types:
      - completed
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: pushup-website
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Download Pushup executable
        uses: actions/download-artifact@v3
        with:
          name: pushup-exe
      - name: Set Pushup exe perms
        run: chmod +x pushup
      - name: Build the Pushup site
        run: ../pushup build
        working-directory: ./docs
      - run: flyctl deploy --remote-only
        working-directory: ./docs
  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Not building Pushup website due to failure of build/test workflow"
